import os
import pandas as pd
from typing import Optional, Tuple
import re

# 示例的STANDARD_FIELDS和SORTKEY，可按实际扩充
STANDARD_FIELDS = {
    'AG':['STUDYID','DOMAIN','USUBJID','AGSEQ','AGGRPID','AGSPID','AGLNKID','AGLNKGRP','AGTRT','AGMODIFY','AGDECOD','AGCAT','AGSCAT','AGPRESP','AGOCCUR','AGSTAT','AGREASND','AGCLAS','AGCLASCD','AGDOSE','AGDOSTXT','AGDOSU','AGDOSFRM','AGDOSFRQ','AGROUTE','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','AGSTDTC','AGENDTC','AGSTDY','AGENDY','AGDUR','AGSTRF','AGENRF','AGSTRTPT','AGSTTPT','AGENRTPT','AGENTPT'],
    'CM':['STUDYID','DOMAIN','USUBJID','CMSEQ','CMGRPID','CMSPID','CMTRT','CMMODIFY','CMDECOD','CMCAT','CMSCAT','CMPRESP','CMOCCUR','CMSTAT','CMREASND','CMINDC','CMCLAS','CMCLASCD','CMDOSE','CMDOSTXT','CMDOSU','CMDOSFRM','CMDOSFRQ','CMDOSTOT','CMDOSRGM','CMROUTE','CMADJ','CMRSDISC','TAETORD','EPOCH','CMSTDTC','CMENDTC','CMSTDY','CMENDY','CMDUR','CMSTRF','CMENRF','CMSTRTPT','CMSTTPT','CMENRTPT','CMENTPT'],
    'EC':['STUDYID','DOMAIN','USUBJID','ECSEQ','ECGRPID','ECREFID','ECSPID','ECLNKID','ECLNKGRP','ECTRT','ECMOOD','ECCAT','ECSCAT','ECPRESP','ECOCCUR','ECREASOC','ECDOSE','ECDOSTXT','ECDOSU','ECDOSFRM','ECDOSFRQ','ECDOSTOT','ECDOSRGM','ECROUTE','ECLOT','ECLOC','ECLAT','ECDIR','ECPORTOT','ECFAST','ECPSTRG','ECPSTRGU','ECADJ','TAETORD','EPOCH','ECSTDTC','ECENDTC','ECSTDY','ECENDY','ECDUR','ECTPT','ECTPTNUM','ECELTM','ECTPTREF','ECRFTDTC'],
    'EX':['STUDYID','DOMAIN','USUBJID','EXSEQ','EXGRPID','EXREFID','EXSPID','EXLNKID','EXLNKGRP','EXTRT','EXCAT','EXSCAT','EXDOSE','EXDOSTXT','EXDOSU','EXDOSFRM','EXDOSFRQ','EXDOSRGM','EXROUTE','EXLOT','EXLOC','EXLAT','EXDIR','EXFAST','EXADJ','TAETORD','EPOCH','EXSTDTC','EXENDTC','EXSTDY','EXENDY','EXDUR','EXTPT','EXTPTNUM','EXELTM','EXTPTREF','EXRFTDTC'],
    'ML':['STUDYID','DOMAIN','USUBJID','MLSEQ','MLGRPID','MLSPID','MLTRT','MLCAT','MLSCAT','MLPRESP','MLOCCUR','MLSTAT','MLREASND','MLDOSE','MLDOSTXT','MLDOSU','MLDOSFRM','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','MLDTC','MLSTDTC','MLENDTC','MLDY','MLSTDY','MLENDY','MLDUR','MLTPT','MLTPTNUM','MLELTM','MLTPTREF','MLRFTDTC','MIDS','RELMIDS','MIDSDTC'],
    'PR':['STUDYID','DOMAIN','USUBJID','PRSEQ','PRGRPID','PRSPID','PRLNKID','PRLNKGRP','PRTRT','PRDECOD','PRCAT','PRSCAT','PRPRESP','PROCCUR','PRINDC','PRDOSE','PRDOSTXT','PRDOSU','PRDOSFRM','PRDOSFRQ','PRDOSRGM','PRROUTE','PRLOC','PRLAT','PRDIR','PRPORTOT','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','PRSTDTC','PRENDTC','PRSTDY','PRENDY','PRDUR','PRTPT','PRTPTNUM','PRELTM','PRTPTREF','PRRFTDTC','PRSTRTPT','PRSTTPT','PRENRTPT','PRENTPT'],
    'SU':['STUDYID','DOMAIN','USUBJID','SUSEQ','SUGRPID','SUSPID','SUTRT','SUMODIFY','SUDECOD','SUCAT','SUSCAT','SUPRESP','SUOCCUR','SUSTAT','SUREASND','SUCLAS','SUCLASCD','SUDOSE','SUDOSTXT','SUDOSU','SUDOSFRM','SUDOSFRQ','SUDOSTOT','SUROUTE','TAETORD','EPOCH','SUSTDTC','SUENDTC','SUSTDY','SUENDY','SUDUR','SUSTRF','SUENRF','SUSTRTPT','SUSTTPT','SUENRTPT','SUENTPT'],
    'AE':['STUDYID','DOMAIN','USUBJID','SPDEVID','AESEQ','AEGRPID','AEREFID','AESPID','AETERM','AEMODIFY','AELLT','AELLTCD','AEDECOD','AEPTCD','AEHLT','AEHLTCD','AEHLGT','AEHLGTCD','AECAT','AESCAT','AEPRESP','AEBODSYS','AEBDSYCD','AESOC','AESOCCD','AELOC','AESEV','AESER','AEACN','AEACNOTH','AEACNDEV','AEREL','AERLDEV','AERELNST','AEPATT','AEOUT','AESCAN','AESCONG','AESDISAB','AESDTH','AESHOSP','AESLIFE','AESOD','AESMIE','AESINTV','AEUNANT','AERLPRT','AERLPRC','AECONTRT','AETOXGR','TAETORD','EPOCH','AESTDTC','AEENDTC','AESTDY','AEENDY','AEDUR','AEENRF','AEENRTPT','AEENTPT'],
    'BE':['STUDYID','DOMAIN','USUBJID','SPDEVID','BESEQ','BEGRPID','BEREFID','BESPID','BETERM','BEMODIFY','BEDECOD','BECAT','BESCAT','BELOC','BEPARTY','BEPRTYID','VISITNUM','VISIT','VISITDY','BEDTC','BESTDTC','BEENDTC','BESTDY','BEENDY','BEDUR'],
    'CE':['STUDYID','DOMAIN','USUBJID','CESEQ','CEGRPID','CEREFID','CESPID','CETERM','CEDECOD','CECAT','CESCAT','CEPRESP','CEOCCUR','CESTAT','CEREASND','CEBODSYS','CESEV','CETOXGR','TAETORD','EPOCH','CEDTC','CESTDTC','CEENDTC','CEDY','CESTDY','CEENDY','CESTRF','CEENRF','CESTRTPT','CESTTPT','CEENRTPT','CEENTPT'],
    'DS':['STUDYID','DOMAIN','USUBJID','DSSEQ','DSGRPID','DSREFID','DSSPID','DSTERM','DSDECOD','DSCAT','DSSCAT','EPOCH','DSDTC','DSSTDTC','DSDY','DSSTDY'],
    'DV':['STUDYID','DOMAIN','USUBJID','DVSEQ','DVREFID','DVSPID','DVTERM','DVDECOD','DVCAT','DVSCAT','TAETORD','EPOCH','DVSTDTC','DVENDTC','DVSTDY','DVENDY'],
    'HO':['STUDYID','DOMAIN','USUBJID','HOSEQ','HOGRPID','HOREFID','HOSPID','HOTERM','HODECOD','HOCAT','HOSCAT','HOPRESP','HOOCCUR','HOSTAT','HOREASND','TAETORD','EPOCH','HODTC','HOSTDTC','HOENDTC','HODY','HOSTDY','HOENDY','HODUR','HOSTRTPT','HOSTTPT','HOENRTPT','HOENTPT'],
    'MH':['STUDYID','DOMAIN','USUBJID','MHSEQ','MHGRPID','MHREFID','MHSPID','MHTERM','MHMODIFY','MHDECOD','MHEVDTYP','MHCAT','MHSCAT','MHPRESP','MHOCCUR','MHSTAT','MHREASND','MHBODSYS','TAETORD','EPOCH','MHDTC','MHSTDTC','MHENDTC','MHDY','MHENRF','MHENRTPT','MHENTPT'],
    'BS':['STUDYID','DOMAIN','USUBJID','SPDEVID','BSSEQ','BSGRPID','BSREFID','BSSPID','BSTESTCD','BSTEST','BSCAT','BSSCAT','BSORRES','BSORRESU','BSSTRESC','BSSTRESN','BSSTRESU','BSSTAT','BSREASND','BSNAM','BSSPEC','BSANTREG','BSSPCCND','BSMETHOD','BSBLFL','VISITNUM','VISIT','VISITDY','BSDTC','BSDY','BSTPT','BSTPTNUM','BSELTM','BSTPTREF','BSRFTDTC'],
    'CP':['STUDYID','DOMAIN','USUBJID','CPSEQ','CPGRPID','CPREFID','CPSPID','CPLNKID','CPLNKGRP','CPTESTCD','CPTEST','CPSBMRKS','CPCELSTA','CPCSMRKS','CPTSTCND','CPCNDAGT','CPBDAGNT','CPABCLID','CPMRKSTR','CPGATE','CPGATDEF','CPSPTSTD','CPCAT','CPSCAT','CPTSTPNL','CPORRES','CPORRESU','CPRESSCL','CPRESTYP','CPCOLSRT','CPORNRLO','CPORNRHI','CPSTRESC','CPSTRESN','CPSTRESU','CPSTNRLO','CPSTNRHI','CPNRIND','CPSTAT','CPREASND','CPNAM','CPLOINC','CPSPEC','CPSPCCND','CPMETHOD','CPANMETH','CPLOBXFL','CPBLFL','CPDRVFL','CPCLSIG','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','CPDTC','CPDY','CPTPT','CPTPTNUM','CPELTM','CPTPTREF','CPRFTDTC'],
    'CV':['STUDYID','DOMAIN','USUBJID','CVSEQ','CVGRPID','CVREFID','CVSPID','CVLNKID','CVLNKGRP','CVTESTCD','CVTEST','CVCAT','CVSCAT','CVPOS','CVORRES','CVORRESU','CVSTRESC','CVSTRESN','CVSTRESU','CVSTAT','CVREASND','CVLOC','CVLAT','CVDIR','CVMETHOD','CVLOBXFL','CVBLFL','CVDRVFL','CVEVAL','CVEVALID','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','CVDTC','CVDY','CVTPT','CVTPTNUM','CVELTM','CVTPTREF','CVRFTDTC'],
    'DA':['STUDYID','DOMAIN','USUBJID','DASEQ','DAGRPID','DAREFID','DASPID','DALNKID','DALNKGRP','DATESTCD','DATEST','DACAT','DASCAT','DAORRES','DAORRESU','DASTRESC','DASTRESN','DASTRESU','DASTAT','DAREASND','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','DADTC','DADY'],
    'DD':['STUDYID','DOMAIN','USUBJID','DDSEQ','DDTESTCD','DDTEST','DDORRES','DDSTRESC','DDRESCAT','DDEVAL','DDDTC','DDDY'],
    'EG':['STUDYID','DOMAIN','USUBJID','SPDEVID','EGSEQ','EGGRPID','EGREFID','EGSPID','EGBEATNO','EGTESTCD','EGTEST','EGCAT','EGSCAT','EGPOS','EGORRES','EGORRESU','EGSTRESC','EGSTRESN','EGSTRESU','EGSTAT','EGREASND','EGNAM','EGMETHOD','EGLEAD','EGLOBXFL','EGBLFL','EGDRVFL','EGEVAL','EGEVALID','EGCLSIG','EGREPNUM','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','EGDTC','EGDY','EGTPT','EGTPTNUM','EGELTM','EGTPTREF','EGRFTDTC'], 
    'FT':['STUDYID','DOMAIN','USUBJID','FTSEQ','FTGRPID','FTREFID','FTSPID','FTTESTCD','FTTEST','FTCAT','FTSCAT','FTPOS','FTORRES','FTORRESU','FTSTRESC','FTSTRESN','FTSTRESU','FTSTAT','FTREASND','FTNAM','FTMETHOD','FTLOBXFL','FTBLFL','FTDRVFL','FTREPNUM','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','FTDTC','FTDY','FTTPT','FTTPTNUM','FTELTM','FTTPTREF','FTRFTDTC'],
    'GF':['STUDYID','DOMAIN','USUBJID','SPDEVID','NHOID','GFSEQ','GFGRPID','GFREFID','GFSPID','GFLNKID','GFLNKGRP','GFTESTCD','GFTEST','GFTSTDTL','GFCAT','GFSCAT','GFORRES','GFORRESU','GFORREF','GFSTRESC','GFSTRESN','GFSTRESU','GFSTREFC','GFSTREFN','GFRESCAT','GFINHERT','GFGENREF','GFCHROM','GFSYM','GFSYMTYP','GFGENLOC','GFGENSR','GFSEQID','GFPVRID','GFCOPYID','GFSTAT','GFREASND','GFNAM','GFSPEC','GFMETHOD','GFRUNID','GFANMETH','GFBLFL','GFDRVFL','GFLLOQ','GFREPNUM','VISITNUM','VISIT','VISITDY','GFDTC','GFDY','GFTPT','GFTPTNUM','GFELTM','GFTPTREF','GFRFTDTC'],
    'IE':['STUDYID','DOMAIN','USUBJID','IESEQ','IESPID','IETESTCD','IETEST','IECAT','IESCAT','IEORRES','IESTRESC','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','IEDTC','IEDY'],
    'IS':['STUDYID','DOMAIN','USUBJID','NHOID','ISSEQ','ISGRPID','ISREFID','ISSPID','ISTESTCD','ISTEST','ISTSTCND','ISCNDAGT','ISBDAGNT','ISTSTOPO','ISMSCBCE','ISTSTDTL','ISCAT','ISSCAT','ISORRES','ISORRESU','ISORNRLO','ISORNRHI','ISSTRESC','ISSTRESN','ISSTRESU','ISSTNRLO','ISSTNRHI','ISSTNRC','ISNRIND','ISSTAT','ISREASND','ISNAM','ISSPEC','ISSPCCND','ISSPCUFL','ISMETHOD','ISLOBXFL','ISBLFL','ISDRVFL','ISLLOQ','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','ISDTC','ISENDTC','ISDY','ISENDY','ISTPT','ISTPTNUM','ISELTM','ISTPTREF','ISRFTDTC'],
    'LB':['STUDYID','DOMAIN','USUBJID','LBSEQ','LBGRPID','LBREFID','LBSPID','LBTESTCD','LBTEST','LBTSTCND','LBBDAGNT','LBTSTOPO','LBCAT','LBSCAT','LBORRES','LBORRESU','LBRESSCL','LBRESTYP','LBCOLSRT','LBORNRLO','LBORNRHI','LBLLOD','LBSTRESC','LBSTRESN','LBSTRESU','LBSTNRLO','LBSTNRHI','LBSTNRC','LBNRIND','LBSTAT','LBREASND','LBNAM','LBLOINC','LBSPEC','LBSPCCND','LBSPCUFL','LBMETHOD','LBANMETH','LBTMTHSN','LBLOBXFL','LBBLFL','LBFAST','LBDRVFL','LBTOX','LBTOXGR','LBCLSIG','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','LBDTC','LBENDTC','LBDY','LBENDY','LBTPT','LBTPTNUM','LBELTM','LBTPTREF','LBRFTDTC','LBPTFL','LBPDUR'],
    'MB':['STUDYID','DOMAIN','USUBJID','FOCID','MBSEQ','MBGRPID','MBREFID','MBSPID','MBLNKID','MBLNKGRP','MBTESTCD','MBTEST','MBTSTDTL','MBCAT','MBSCAT','MBORRES','MBORRESU','MBSTRESC','MBSTRESN','MBSTRESU','MBRESCAT','MBSTAT','MBREASND','MBNAM','MBLOINC','MBSPEC','MBSPCCND','MBLOC','MBLAT','MBDIR','MBMETHOD','MBLOBXFL','MBBLFL','MBFAST','MBDRVFL','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','MBDTC','MBDY','MBTPT','MBTPTNUM','MBELTM','MBTPTREF','MBRFTDTC'],
    'MI':['STUDYID','DOMAIN','USUBJID','MISEQ','MIGRPID','MIREFID','MISPID','MITESTCD','MITEST','MITSTDTL','MICAT','MISCAT','MIORRES','MIORRESU','MISTRESC','MISTRESN','MISTRESU','MIRESCAT','MISTAT','MIREASND','MINAM','MISPEC','MISPCCND','MILOC','MILAT','MIDIR','MIMETHOD','MILOBXFL','MIBLFL','MIEVAL','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','MIDTC','MIDY'],
    'MK':['STUDYID','DOMAIN','USUBJID','MKSEQ','MKGRPID','MKREFID','MKSPID','MKLNKID','MKLNKGRP','MKTESTCD','MKTEST','MKCAT','MKSCAT','MKPOS','MKORRES','MKORRESU','MKSTRESC','MKSTRESN','MKSTRESU','MKSTAT','MKREASND','MKLOC','MKLAT','MKDIR','MKMETHOD','MKLOBXFL','MKBLFL','MKDRVFL','MKEVAL','MKEVALID','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','MKDTC','MKDY','MKTPT','MKTPTNUM','MKELTM','MKTPTREF','MKRFTDTC'],
    'MS':['STUDYID','DOMAIN','USUBJID','NHOID','MSSEQ','MSGRPID','MSREFID','MSSPID','MSLNKID','MSTESTCD','MSTEST','MSAGENT','MSCONC','MSCONCU','MSTSTDTL','MSCAT','MSSCAT','MSORRES','MSORRESU','MSSTRESC','MSSTRESN','MSSTRESU','MSNRIND','MSRESCAT','MSSTAT','MSREASND','MSNAM','MSLOINC','MSSPEC','MSSPCCND','MSLOC','MSLAT','MSDIR','MSMETHOD','MSANMETH','MSLOBXFL','MSBLFL','MSFAST','MSDRVFL','MSEVAL','MSEVALID','MSACPTFL','MSLLOQ','MSULOQ','MSREPNUM','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','MSDTC','MSDY','MSDUR','MSTPT','MSTPTNUM','MSELTM','MSTPTREF','MSRFTDTC','MSEVLINT','MSEVINTX'],
    'NV':['STUDYID','DOMAIN','USUBJID','FOCID','NVSEQ','NVGRPID','NVREFID','NVSPID','NVLNKID','NVLNKGRP','NVTESTCD','NVTEST','NVCAT','NVSCAT','NVORRES','NVORRESU','NVSTRESC','NVSTRESN','NVSTRESU','NVSTAT','NVREASND','NVLOC','NVLAT','NVDIR','NVMETHOD','NVLOBXFL','NVBLFL','NVDRVFL','NVEVAL','NVEVALID','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','NVDTC','NVDY','NVTPT','NVTPTNUM','NVELTM','NVTPTREF','NVRFTDTC'],
    'OE':['STUDYID','DOMAIN','USUBJID','FOCID','OESEQ','OEGRPID','OELNKID','OELNKGRP','OETESTCD','OETEST','OETSTDTL','OECAT','OESCAT','OEORRES','OEORRESU','OEORNRLO','OEORNRHI','OESTRESC','OESTRESN','OESTRESU','OESTNRLO','OESTNRHI','OESTNRC','OENRIND','OERESCAT','OESTAT','OEREASND','OELOC','OELAT','OEDIR','OEPORTOT','OEMETHOD','OELOBXFL','OEBLFL','OEDRVFL','OEEVAL','OEEVALID','OEACPTFL','OEREPNUM','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','OEDTC','OEDY','OETPT','OETPTNUM','OEELTM','OETPTREF','OERFTDTC'],
    'PC':['STUDYID','DOMAIN','USUBJID','PCSEQ','PCGRPID','PCREFID','PCSPID','PCTESTCD','PCTEST','PCCAT','PCSCAT','PCORRES','PCORRESU','PCSTRESC','PCSTRESN','PCSTRESU','PCSTAT','PCREASND','PCNAM','PCSPEC','PCSPCCND','PCMETHOD','PCFAST','PCDRVFL','PCLLOQ','PCULOQ','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','PCDTC','PCENDTC','PCDY','PCENDY','PCTPT','PCTPTNUM','PCELTM','PCTPTREF','PCRFTDTC','PCEVLINT'],
    'PE':['STUDYID','DOMAIN','USUBJID','PESEQ','PEGRPID','PESPID','PETESTCD','PETEST','PEMODIFY','PECAT','PESCAT','PEBODSYS','PEORRES','PEORRESU','PESTRESC','PESTAT','PEREASND','PELOC','PELAT','PEMETHOD','PELOBXFL','PEBLFL','PEEVAL','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','PEDTC','PEDY'],
    'PP':['STUDYID','DOMAIN','USUBJID','PPSEQ','PPGRPID','PPTESTCD','PPTEST','PPCAT','PPSCAT','PPORRES','PPORRESU','PPSTRESC','PPSTRESN','PPSTRESU','PPSTAT','PPREASND','PPSPEC','PPANMETH','TAETORD','EPOCH','PPDTC','PPDY','PPTPTREF','PPRFTDTC','PPSTINT','PPENINT'],
    'QS':['STUDYID','DOMAIN','USUBJID','QSSEQ','QSGRPID','QSSPID','QSTESTCD','QSTEST','QSCAT','QSSCAT','QSORRES','QSORRESU','QSSTRESC','QSSTRESN','QSSTRESU','QSSTAT','QSREASND','QSMETHOD','QSLOBXFL','QSBLFL','QSDRVFL','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','QSDTC','QSDY','QSTPT','QSTPTNUM','QSELTM','QSTPTREF','QSRFTDTC','QSEVLINT','QSEVINTX'],
    'RE':['STUDYID','DOMAIN','USUBJID','SPDEVID','RESEQ','REGRPID','REREFID','RESPID','RELNKID','RELNKGRP','RETESTCD','RETEST','RECAT','RESCAT','REPOS','REORRES','REORRESU','REORREF','RESTRESC','RESTRESN','RESTRESU','RESTREFC','RESTREFN','RESTAT','REREASND','RELOC','RELAT','REDIR','REMETHOD','RELOBXFL','REBLFL','REDRVFL','REEVAL','REEVALID','REREPNUM','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','REDTC','REDY','RETPT','RETPTNUM','REELTM','RETPTREF','RERFTDTC'],
    'RP':['STUDYID','DOMAIN','USUBJID','RPSEQ','RPGRPID','RPREFID','RPSPID','RPLNKID','RPLNKGRP','RPTESTCD','RPTEST','RPCAT','RPSCAT','RPORRES','RPORRESU','RPSTRESC','RPSTRESN','RPSTRESU','RPSTAT','RPREASND','RPLOBXFL','RPBLFL','RPDRVFL','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','RPDTC','RPDY','RPDUR','RPTPT','RPTPTNUM','RPELTM','RPTPTREF','RPRFTDTC'],
    'RS':['STUDYID','DOMAIN','USUBJID','RSSEQ','RSGRPID','RSREFID','RSSPID','RSLNKID','RSLNKGRP','RSTESTCD','RSTEST','RSCAT','RSSCAT','RSORRES','RSORRESU','RSSTRESC','RSSTRESN','RSSTRESU','RSSTAT','RSREASND','RSNAM','RSMETHOD','RSLOBXFL','RSBLFL','RSDRVFL','RSEVAL','RSEVALID','RSACPTFL','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','RSDTC','RSDY','RSTPT','RSTPTNUM','RSELTM','RSTPTREF','RSRFTDTC','RSEVLINT','RSEVINTX','RSSTRTPT','RSSTTPT','RSENRTPT','RSENTPT'],
    'SC':['STUDYID','DOMAIN','USUBJID','SCSEQ','SCGRPID','SCSPID','SCTESTCD','SCTEST','SCCAT','SCSCAT','SCORRES','SCORRESU','SCSTRESC','SCSTRESN','SCSTRESU','SCSTAT','SCREASND','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','SCDTC','SCDY'],
    'SS':['STUDYID','DOMAIN','USUBJID','SSSEQ','SSGRPID','SSSPID','SSTESTCD','SSTEST','SSCAT','SSSCAT','SSORRES','SSSTRESC','SSSTAT','SSREASND','SSEVAL','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','SSDTC','SSDY'],
    'TR':['STUDYID','DOMAIN','USUBJID','TRSEQ','TRGRPID','TRREFID','TRSPID','TRLNKID','TRLNKGRP','TRTESTCD','TRTEST','TRORRES','TRORRESU','TRSTRESC','TRSTRESN','TRSTRESU','TRSTAT','TRREASND','TRNAM','TRMETHOD','TRLOBXFL','TRBLFL','TREVAL','TREVALID','TRACPTFL','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','TRDTC','TRDY'],
    'TU':['STUDYID','DOMAIN','USUBJID','TUSEQ','TUGRPID','TUREFID','TUSPID','TULNKID','TULNKGRP','TUTESTCD','TUTEST','TUORRES','TUSTRESC','TUNAM','TULOC','TULAT','TUDIR','TUPORTOT','TUMETHOD','TULOBXFL','TUBLFL','TUEVAL','TUEVALID','TUACPTFL','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','TUDTC','TUDY'],
    'UR':['STUDYID','DOMAIN','USUBJID','URSEQ','URGRPID','URREFID','URSPID','URLNKID','URLNKGRP','URTESTCD','URTEST','URTSTDTL','URCAT','URSCAT','URORRES','URORRESU','URSTRESC','URSTRESN','URSTRESU','URRESCAT','URSTAT','URREASND','URLOC','URLAT','URDIR','URMETHOD','URLOBXFL','URBLFL','URDRVFL','UREVAL','UREVALID','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','URDTC','URDY','URTPT','URTPTNUM','URELTM','URTPTREF','URRFTDTC'],
    'VS':['STUDYID','DOMAIN','USUBJID','VSSEQ','VSGRPID','VSSPID','VSTESTCD','VSTEST','VSCAT','VSSCAT','VSPOS','VSORRES','VSORRESU','VSSTRESC','VSSTRESN','VSSTRESU','VSSTAT','VSREASND','VSLOC','VSLAT','VSLOBXFL','VSBLFL','VSDRVFL','VSTOX','VSTOXGR','VSCLSIG','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','VSDTC','VSDY','VSTPT','VSTPTNUM','VSELTM','VSTPTREF','VSRFTDTC'],
    'FA':['STUDYID','DOMAIN','USUBJID','FASEQ','FAGRPID','FASPID','FATESTCD','FATEST','FAOBJ','FACAT','FASCAT','FAORRES','FAORRESU','FASTRESC','FASTRESN','FASTRESU','FASTAT','FAREASND','FALOC','FALAT','FALOBXFL','FABLFL','FAEVAL','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','FADTC','FADY'],
    'SR':['STUDYID','DOMAIN','USUBJID','SRSEQ','SRGRPID','SRREFID','SRSPID','SRTESTCD','SRTEST','SROBJ','SRCAT','SRSCAT','SRORRES','SRORRESU','SRSTRESC','SRSTRESN','SRSTRESU','SRSTAT','SRREASND','SRNAM','SRSPEC','SRLOC','SRLAT','SRMETHOD','SRLOBXFL','SRBLFL','SREVAL','VISITNUM','VISIT','VISITDY','TAETORD','EPOCH','SRDTC','SRDY','SRTPT','SRTPTNUM','SRELTM','SRTPTREF','SRRFTDTC'],
    'CO':['STUDYID','DOMAIN','RDOMAIN','USUBJID','COSEQ','IDVAR','IDVARVAL','COREF','COVAL','COEVAL','COEVALID','CODTC','CODY'],
    'DM':['STUDYID','DOMAIN','USUBJID','SUBJID','RFSTDTC','RFENDTC','RFXSTDTC','RFXENDTC','RFCSTDTC','RFCENDTC','RFICDTC','RFPENDTC','DTHDTC','DTHFL','SITEID','INVID','INVNAM','BRTHDTC','AGE','AGEU','SEX','RACE','ETHNIC','ARMCD','ARM','ACTARMCD','ACTARM','ARMNRS','ACTARMUD','COUNTRY','DMDTC','DMDY'],
    'SE':['STUDYID','DOMAIN','USUBJID','SESEQ','ETCD','ELEMENT','TAETORD','EPOCH','SESTDTC','SEENDTC','SESTDY','SEENDY','SEUPDES'],
    'SM':['STUDYID','DOMAIN','USUBJID','SMSEQ','MIDS','MIDSTYPE','SMSTDTC','SMENDTC','SMSTDY','SMENDY'],
}

SORTKEY = {
    "IE": ["USUBJID", "SUPPSEQ", "IETESTCD", "IECAT", "IESCAT"],
    "SE": ["USUBJID", "SUPPSEQ", "EPOCH", "SESTDTC"],
    "SS": ["USUBJID", "SUPPSEQ", "SSSTRESC", "SSDTC"],
    "DS": ["USUBJID", "SUPPSEQ", "DSDECOD", "DSREFID", "DSSTDTC"],
    "DM": ["USUBJID", "SUPPSEQ"],
    "SU": ["USUBJID", "SUPPSEQ", "SUTRT"],
    "MH": ["USUBJID", "SUPPSEQ", "MHGRPID", "MHDECOD", "MHOCCUR"],
    "MI": ["USUBJID", "SUPPSEQ", "MISTRESC", "MIDTC"],
    "BE": ["USUBJID", "SUPPSEQ", "BECAT", "BEREFID", "BEDTC"],
    "GF": ["USUBJID", "SUPPSEQ", "GFSYM", "GFTSTDTL", "GFRESCAT", "GFDTC"],
    "TU": ["USUBJID", "SUPPSEQ", "TUSTRESC", "TULOC", "TUDTC"],
    "TR": ["USUBJID", "SUPPSEQ", "EPOCH", "TRLNKID", "TRDTC"],
    "RS": ["USUBJID", "SUPPSEQ", "EPOCH", "RSTESTCD", "RSDTC"],
    "PR": ["USUBJID", "SUPPSEQ", "PRDECOD", "PRLOC", "PRSTDTC"],
    "CM": ["USUBJID", "SUPPSEQ", "EPOCH", "CMCAT", "CMSCAT", "CMSTDTC"]
}

class FileRestructure:
    @staticmethod
    def file_restructure(input_file: str, output_path: Optional[str] = None, studyid: str = "CIRCULATE") -> Tuple[bool, str]:
        try:
            # 文件名（不带扩展名）作为关键字，如 AB.xlsx => AB
            base_name = os.path.splitext(os.path.basename(input_file))[0]
            key = re.match(r'[A-Za-z]+', base_name).group()

            # 加载所有sheet
            xls = pd.read_excel(input_file, sheet_name=None, dtype=str, engine='openpyxl', na_filter=False)
                        
            # 合并的dataframe列表
            df_list = []

            # 构建所有字段的全集（用于最终纵向合并）
            all_columns = set(STANDARD_FIELDS[key] + ['SUPPSEQ'])

            # 在处理每个 DataFrame 时，检测日期列并格式化为 ISO8601 格式
            for sheet_name, df in xls.items():
                seq = None
                # 检查是否是标准命名方式：AB1、AB12 等
                match_standard = re.match(rf'^{key}(\d+)$', sheet_name)
                if match_standard:
                    seq = match_standard.group(1).zfill(3)
                # 检查是否是默认命名方式：Sheet1、Sheet2 等
                else:
                    match_default = re.match(r'^Sheet(\d+)$', sheet_name)
                    if match_default:
                        seq = match_default.group(1).zfill(3)
                
                # 如果没有匹配到任何命名模式，则跳过此sheet
                if seq is None:
                    continue

                df['SUPPSEQ'] = seq

                # 如果有为"SUBJID"的字段，则改为"USUBJID"，否则不做处理
                if 'SUBJID' in df.columns:
                    df.rename(columns={'SUBJID': 'USUBJID'}, inplace=True)
                
                # 检测并格式化日期列
                for col in df.columns:
                    try:
                        # 创建一个副本以尝试转换为日期
                        temp_col = pd.to_datetime(df[col], errors='coerce')
                        
                        # 如果列中有非空值且全为日期类型，则格式化为 YYYY-MM-DD
                        if not temp_col.isna().all():
                            df[col] = temp_col.dt.strftime('%Y-%m-%d').fillna(df[col])  # 保留原始非日期值
                    except Exception:
                        # 如果转换失败，跳过该列
                        pass

                # 补全缺失列
                missing_cols = [col for col in STANDARD_FIELDS[key] if col not in df.columns]
                for col in missing_cols:
                    df[col] = ""

                # 重新排序：按STANDARD_FIELDS顺序 + 其它列
                standard_cols = STANDARD_FIELDS[key]
                other_cols = [col for col in df.columns if col not in standard_cols and col != 'SUPPSEQ']
                ordered_cols = standard_cols + ['SUPPSEQ'] + sorted(other_cols)
                df = df.reindex(columns=ordered_cols)

                # 收集字段全集
                all_columns.update(df.columns)

                df_list.append(df)

            if not df_list:
                return False, "未读取到符合格式的sheet"

            # 获取全集列顺序（STANDARD_FIELDS顺序 + SUPPSEQ + 其它列）
            final_cols = STANDARD_FIELDS[key] + ['SUPPSEQ']
            all_other_cols = sorted(all_columns - set(final_cols))
            final_cols += all_other_cols

            # 所有数据统一列补全
            for i in range(len(df_list)):
                for col in final_cols:
                    if col not in df_list[i].columns:
                        df_list[i][col] = ""
                df_list[i] = df_list[i][final_cols]

            # 合并
            full_df = pd.concat(df_list, ignore_index=True)

            # 排序
            sort_cols = SORTKEY[key]
            for col in sort_cols:
                if col not in full_df.columns:
                    full_df[col] = ""  # 缺失排序字段也填空
            full_df.sort_values(by=sort_cols, inplace=True, ignore_index=True)
            
            # 添加常量字段STUDYID和DOMAIN
            full_df['STUDYID'] = studyid
            full_df['DOMAIN'] = base_name
            
            # 去除完全相同的重复行
            full_df = full_df.drop_duplicates()
            
            # 如果有f"{base_name}SEQ"字段，则以每个USUBJID字段为基准，增加序号并赋值给f"{base_name}SEQ"
            seq_col = f"{base_name}SEQ"
            if seq_col in full_df.columns:
                full_df[seq_col] = full_df.groupby('USUBJID').cumcount() + 1
                full_df[seq_col] = full_df[seq_col].astype(str)
            
            # 删除字段SUPPSEQ
            full_df.drop(columns=['SUPPSEQ'], inplace=True)
            
            # 写出前确保所有日期列为字符串格式
            for col in full_df.columns:
                if full_df[col].dtype == 'datetime64[ns]':  # 检查是否为日期类型
                    full_df[col] = full_df[col].dt.strftime('%Y-%m-%d')

            # 生成输出路径
            if output_path:
                output_file = os.path.join(output_path, f"{base_name}.csv")
            else:
                output_file = os.path.splitext(input_file)[0] + '.csv'

            # 写出 CSV 文件
            full_df.to_csv(output_file, index=False, encoding='utf-8-sig')

            return True, ""

        except Exception as e:
            return False, str(e)
